from enum import Enum

class AudioProcessingStatus(str, Enum):
    PENDING = "PENDING"
    AUDIO_EXTRACTING = "AUDIO_EXTRACTING"
    AUDIO_ANALYZING = "AUDIO_ANALYZING"
    AUDIO_NORMALIZING = "AUDIO_NORMALIZING"
    READY_FOR_TRANSCRIPTION = "READY_FOR_TRANSCRIPTION"
    AUDIO_CORRUPTED = "AUDIO_CORRUPTED"
    EMPTY_AUDIO = "EMPTY_AUDIO"
    FAILED = "FAILED"

class AudioQuality(str, Enum):
    GOOD = "GOOD"
    ACCEPTABLE = "ACCEPTABLE"
    POOR = "POOR"
    UNUSABLE = "UNUSABLE"
