from enum import Enum

class MediaStatus(str, Enum):
    CREATED = "CREATED"
    UPLOAD_PENDING = "UPLOAD_PENDING"
    UPLOADED = "UPLOADED"
    SCANNING = "SCANNING"
    VALIDATED = "VALIDATED"
    METADATA_EXTRACTING = "METADATA_EXTRACTING"
    PROCESSING_QUEUED = "PROCESSING_QUEUED"
    PROCESSING = "PROCESSING"
    READY = "READY"
    FAILED = "FAILED"
    QUARANTINED = "QUARANTINED"

class ArtifactType(str, Enum):  
    ORIGINAL_MEDIA = "ORIGINAL_MEDIA"
    NORMALIZED_AUDIO = "NORMALIZED_AUDIO"
