"""media domain schema

Revision ID: 6938da68216e
Revises: 16f51f34384e
Create Date: 2026-09-10 12:17:49.594722
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6938da68216e'
down_revision: Union[str, Sequence[str], None] = '16f51f34384e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_content_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'UPLOAD_PENDING', 'UPLOADED', 'SCANNING', 'VALIDATED', 'METADATA_EXTRACTING', 'PROCESSING_QUEUED', 'PROCESSING', 'READY', 'FAILED', 'QUARANTINED', name='media_status'), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('video_codec', sa.String(length=100), nullable=True),
    sa.Column('audio_codec', sa.String(length=100), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_tenant_id'), 'media_assets', ['tenant_id'], unique=False)
    op.create_table('media_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('ORIGINAL_MEDIA', 'NORMALIZED_AUDIO', name='artifact_type'), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_artifacts_media_asset_id'), 'media_artifacts', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_media_artifacts_tenant_id'), 'media_artifacts', ['tenant_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_media_asset_id'), 'processing_jobs', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_tenant_id'), 'processing_jobs', ['tenant_id'], unique=False)
    op.create_table('upload_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('provider_upload_id', sa.String(length=255), nullable=False),
    sa.Column('parts_count', sa.Integer(), nullable=False),
    sa.Column('part_size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_aborted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_media_asset_id'), 'upload_sessions', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_upload_sessions_tenant_id'), 'upload_sessions', ['tenant_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_upload_sessions_tenant_id'), table_name='upload_sessions')
    op.drop_index(op.f('ix_upload_sessions_media_asset_id'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_index(op.f('ix_processing_jobs_tenant_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_media_asset_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_media_artifacts_tenant_id'), table_name='media_artifacts')
    op.drop_index(op.f('ix_media_artifacts_media_asset_id'), table_name='media_artifacts')
    op.drop_table('media_artifacts')
    op.drop_index(op.f('ix_media_assets_tenant_id'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###